### ISSUE TITLE
Wrong order for xtreemfs::internal::configure::storage "file" resource

### ISSUE THREAD

**Issue by cjeanneret** [wavesoftware/puppet-xtreemfs#2]
The following code creates an error:

``` puppet
file { $object_dir:
  ensure => 'directory',
  owner => 'xtreemfs',
  group => 'xtreemfs',
  before => Anchor[$xtreemfs::internal::workflow::packages],
  notify => Anchor[$xtreemfs::internal::workflow::configure],
}
```

The user "xtreemfs" is created by the package. Thus, it cannot create the directory before the package is installed:

```
Error: /Stage[main]/Xtreemfs::Internal::Configure::Storage/File[/var/lib/xtreemfs]/ensure: change from absent to directory failed: Could not set 'directory' on ensure: Could not find user xtreemfs at 23:/modules/xtreemfs/manifests/internal/configure/storage.pp
```

The main reason this file is created _before_ the package installation seems due to this APT error:

```
mkdir: cannot create directory '/var/lib/xtreemfs': File exists
dpkg: error processing package xtreemfs-server (--configure):
 subprocess installed post-installation script returned error exit status 1
```

Which is a bit ugly — I feel the problem is more at the packaging level than your receipt… I'll contact xtreemfs devs in order to report this error if not already done.

In any cases, right now it seems we're unable to install a "storage" node using the default location.

**Comment by cjeanneret** [comment]
FYI: issue opened [upstreem](https://github.com/xtreemfs/xtreemfs/issues/344)

**Comment by cardil** [comment]
Can't replicate your problem. I've just pushed some acceptance test. Please verify that they work for you:

Ensure you got installed: virtualbox and vagrant.

``` shell
# git clone THIS REPO && cd 
bundle install --path=.vendor
# wait for downloads
bundle exec rake beaker BEAKER_set=ubuntu-server-1404-x64
# wait for tests to be executed
bundle exec rake beaker BEAKER_set=centos-64-x64
# wait for tests to be executed
```

**Comment by cardil** [comment]
Fixed this. I've confirmed this by running only storage test:

``` shell
bundle exec rspec spec/acceptance/role/003_storage_spec.rb
```

Output (fragment from beaker log):

```
ubuntu-server-1404-x64 22:33:25$  env PATH="/usr/bin:/opt/puppet-git-repos/hiera/bin:${PATH}" RUBYLIB="/opt/puppet-git-repos/hiera/lib:/opt/puppet-git-repos/hiera-puppet/lib:${RUBYLIB}" puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.wEcKnc  
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Info: Loading facts
Info: Loading facts
Notice: Compiled catalog for ubuntu-server-1404-x64.suszynski.org in environment production in 0.41 seconds
Info: Applying configuration version '1416432806'
Notice: /Stage[main]/Xtreemfs::Internal::Repo/Apt::Source[xtreemfs]/Apt::Key[Add key: 07D6EA4F2FA7E736 from Apt::Source xtreemfs]/Apt_key[Add key: 07D6EA4F2FA7E736 from Apt::Source xtreemfs]/ensure: created
Notice: /Stage[main]/Apt/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}92afc1e969a04f0764e9ae8343aa9f2f'
Notice: /Stage[main]/Xtreemfs::Internal::Repo/Apt::Source[xtreemfs]/File[xtreemfs.list]/ensure: created
Info: /Stage[main]/Xtreemfs::Internal::Repo/Apt::Source[xtreemfs]/File[xtreemfs.list]: Scheduling refresh of Exec[apt_update]
Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Xtreemfs::Internal::Packages::Server/Package[xtreemfs-server]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Xtreemfs::Internal::Configure::Storage/File[/var/lib/xtreemfs]/group: group changed 'root' to 'xtreemfs'
Info: /Stage[main]/Xtreemfs::Internal::Configure::Storage/File[/var/lib/xtreemfs]: Scheduling refresh of Anchor[xtreemfs::configure]
Notice: /Stage[main]/Xtreemfs::Internal::Workflow/Anchor[xtreemfs::configure]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Xtreemfs::Internal::Workflow/Anchor[xtreemfs::configure]: Scheduling refresh of Anchor[xtreemfs::service]
Info: /Stage[main]/Xtreemfs::Internal::Workflow/Anchor[xtreemfs::configure]: Scheduling refresh of Service[xtreemfs-osd]
Notice: /Stage[main]/Xtreemfs::Role::Storage/Service[xtreemfs-osd]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Xtreemfs::Role::Storage/Service[xtreemfs-osd]: Unscheduling refresh on Service[xtreemfs-osd]
Notice: /Stage[main]/Xtreemfs::Internal::Workflow/Anchor[xtreemfs::service]: Triggered 'refresh' from 1 events
Info: Creating state file /var/lib/puppet/state/state.yaml
Notice: Finished catalog run in 58.04 seconds

ubuntu-server-1404-x64 executed in 59.28 seconds
Exited: 2
    should work without errors

ubuntu-server-1404-x64 22:34:25$  mktemp -t apply_manifest.pp.XXXXXX  
/tmp/apply_manifest.pp.MERt7f

ubuntu-server-1404-x64 executed in 0.04 seconds
localhost $ scp /tmp/beaker20141119-27970-9d9td9 ubuntu-server-1404-x64:/tmp/apply_manifest.pp.MERt7f {:ignore => }

ubuntu-server-1404-x64 22:34:25$  env PATH="/usr/bin:/opt/puppet-git-repos/hiera/bin:${PATH}" RUBYLIB="/opt/puppet-git-repos/hiera/lib:/opt/puppet-git-repos/hiera-puppet/lib:${RUBYLIB}" puppet apply --verbose /tmp/apply_manifest.pp.MERt7f  
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Info: Loading facts
Info: Loading facts
Notice: Compiled catalog for ubuntu-server-1404-x64.suszynski.org in environment production in 0.43 seconds
Info: Applying configuration version '1416432865'
Notice: Finished catalog run in 0.95 seconds

ubuntu-server-1404-x64 executed in 2.21 seconds
    should not make any changes when executed twice
    Service "xtreemfs-osd"

ubuntu-server-1404-x64 22:34:27$  service xtreemfs-osd status && service xtreemfs-osd status | grep 'running'  
XtreemFS Object Storage Device (OSD) is running
XtreemFS Object Storage Device (OSD) is running

ubuntu-server-1404-x64 executed in 0.04 seconds
```
